maps/fy_rambohulk.res 
maps/fy_rambohulk.bsp
maps/fy_rambohulk.txt
gfx/env/xt_deheatbk.tga
gfx/env/xt_deheatdn.tga
gfx/env/xt_deheatft.tga
gfx/env/xt_deheatlf.tga
gfx/env/xt_deheatrt.tga
gfx/env/xt_deheatup.tga
